# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17186501da5d3a6b83342dd727e8e37407df07d3cbbeda89a81eaa795a8d6aafcb4208b97e18a56d8f24f5e6b614cc2fa4e02c571bf41ffc49a995da7b06fa0a

test:
  secret_key_base: 7d930f948bea31155343a1beddcc54c5bcc53ecc8e7b9482be66b4d3201c70dd88f97d21b0ee1ef600ebc8eaf5385d903dc8e964347a67e05dd07fa7063f6de0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
